version: '3.5'
networks:
  exam-network:
    driver: bridge
services:
  python:
    build:
      context: ./
    container_name: exam
    environment:
      - COURSES_HOSTNAME=https://ubademy-14-cursos.herokuapp.com/ 
      - UBADEMY_PASSWORD=
    ports:
      - "8080:8080"
    networks:
      - exam-network