name: Build and Test

on: 'push'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install server dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./service --cov-report=xml
      - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true